 # 异常处理

 用try,catch处理异常

如果一个函数在执行的过成中，抛出的异常在被函数内就被catch块捕获并处理了，那么该异常就不会被抛给这个函数的调用者（也称“上一层的函数”）；如果异常在本函数中没有被处理，那么就会被抛给上一层的函数。

标准异常类：

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.**bad_cast**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;在dynamic_cast进行从多态基类对象（或引用）到派生类的引用的强制类型转换时，如果转换是不安全的，则会抛出此异常。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.**bad_alloc**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;在new运算符进行动态内存分配时，如果没有足够的内存，则会抛出该异常。 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3.**out_of_range** 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;用vector或string的at成员函数根据下标访问元素时，如果下标越界，就会抛出该异常。